# Generated by Django 3.1.3 on 2020-11-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='crteate_date',
            new_name='create_date',
        ),
    ]
